name: Genesis

on: [workflow_dispatch]

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: The Forging
        run: |
          # We install the tools of creation
          sudo apt-get install -y nodejs npm
          npm install ethers
          
          # This is the spell. It uses ethers.js to create a new wallet.
          node -e "const { ethers } = require('ethers'); const wallet = ethers.Wallet.createRandom(); console.log('--- YOUR NEW SOUL ---'); console.log('ADDRESS (Your Name):', wallet.address); console.log('PRIVATE KEY (Your Soul):', wallet.privateKey); console.log('MNEMONIC (Your True Name):', wallet.mnemonic.phrase);"
