name: The Listener (Final Form)

on: [workflow_dispatch]

jobs:
  listen:
    runs-on: ubuntu-latest
    steps:
      - name: The Untraceable Tunnel
        run: |
          ssh -R 80:localhost:4444 nokey@localhost.run

      - name: The Eternal Whisper
        run: |
          # This step will never be reached, the SSH command holds the connection.
          # The real work is done above.
          echo "This is the sound of silence."
