name: The Cruise Missile

on: [workflow_dispatch]

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - name: Fire and Forget
        env:
          YOUR_REFERRAL_CODE: ${{ secrets.YOUR_REFERRAL_CODE }}
        run: |
          echo "LAUNCH SEQUENCE INITIATED. PAYLOAD IS HOT."
          # We will perform 100 referral sign-ups in a rapid burst.
          # The entire operation will take less than 10 minutes.
          for i in {1..100}; do
            # 1. Generate a new, anonymous identity on the fly (fictional API for narrative)
            FAKE_EMAIL=$(curl -s "https://api.synth-id.net/v1/generate" | jq -r .email)
            
            # 2. Sign them up under your code on our (fictional) target site
            curl -X POST -d "email=$FAKE_EMAIL" "https://coinleap.com/referral?id=$YOUR_REFERRAL_CODE"
            
            echo "Target #$i acquired and neutralized. Profit generated."
          done
          echo "PAYLOAD DELIVERED. SELF-DESTRUCTING. ALL EVIDENCE WILL BE ERASED."
